import { CompletionItem } from "vscode-languageserver";

export const keywordList: CompletionItem[] = [
    {label: "for", kind: 14},
    {label: "endfor", kind: 14},
    {label: "if", kind: 14},
    {label: "else", kind: 14},
    {label: "elseif", kind: 14},
    {label: "endif", kind: 14},
    {label: "do", kind: 14},
    {label: "while", kind: 14},
    {label: "switch", kind: 14},
    {label: "strswitch", kind: 14},
    {label: "case", kind: 14},
    {label: "default", kind: 14},
    {label: "break", kind: 14},
    {label: "try", kind: 14},
    {label: "catch", kind: 14},
    {label: "endtry", kind: 14},
    {label: "#pragma", kind: 14},
    {label: "#if", kind: 14},
    {label: "#endif", kind: 14},
    {label: "#ifdef", kind: 14},
    {label: "#ifndef", kind: 14},
    {label: "#include", kind: 14},
    {label: "function", kind: 14},
    {label: "picture", kind: 14},
    {label: "macro", kind: 14},
    {label: "structure", kind: 14},
    {label: "end", kind: 14},
    {label: "endmacro", kind: 14},
    {label: "endstructure", kind: 14},
    {label: "proc", kind: 14},
    {label: "endproc", kind: 14},
    {label: "constant", kind: 14},
    {label: "strconstant", kind: 14},
];