import { CompletionItem } from "vscode-languageserver";

export const keywordList: CompletionItem[] = [
    {label: "for"},
    {label: "endfor"},
    {label: "if"},
    {label: "else"},
    {label: "elseif"},
    {label: "endif"},
    {label: "do"},
    {label: "while"},
    {label: "switch"},
    {label: "strswitch"},
    {label: "case"},
    {label: "default"},
    {label: "break"},
    {label: "try"},
    {label: "catch"},
    {label: "endtry"},
    {label: "#pragma"},
    {label: "#if"},
    {label: "#endif"},
    {label: "#ifdef"},
    {label: "#ifndef"},
    {label: "#include"},
    {label: "function"},
    {label: "picture"},
    {label: "macro"},
    {label: "structure"},
    {label: "end"},
    {label: "endmacro"},
    {label: "endstructure"},
    {label: "proc"},
    {label: "endproc"},
    {label: "constant"},
    {label: "strconstant"},
];